name:
  products_microservice
server:
  port: 8083
spring:
  application:
    name: products_microservice
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/products
    username: postgres
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8087/eureka